apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs2-data
  namespace: game-servers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  # Docker Desktop: "hostpath"
  # minikube:       "standard"
  # k3s:            "local-path"
  storageClassName: hostpath
