apiVersion: v1
kind: Service
metadata:
  name: cs2-service
  namespace: game-servers
spec:
  type: NodePort
  selector:
    app: cs2-server
  ports:
    - name: game-udp
      protocol: UDP
      port: 27015
      targetPort: 27015
      nodePort: 30015
    - name: game-tcp
      protocol: TCP
      port: 27015
      targetPort: 27015
      nodePort: 30016
    - name: sourcetv
      protocol: UDP
      port: 27020
      targetPort: 27020
      nodePort: 30020
