apiVersion: v1
kind: Service
metadata:
  name: insurgency-service
  namespace: game-servers
spec:
  type: NodePort
  selector:
    app: insurgency-server
  ports:
    - name: game-udp
      protocol: UDP
      port: 27015
      targetPort: 27015
      nodePort: 30025
    - name: game-tcp
      protocol: TCP
      port: 27015
      targetPort: 27015
      nodePort: 30026
    - name: sourcetv
      protocol: UDP
      port: 27020
      targetPort: 27020
      nodePort: 30027
