// Hand-written mirrors of the backend's C# records (GameDashboard.Api/Models).
// The backend has no OpenAPI document; these shapes are locked by its contract
// tests (ApiContractTests.cs), camelCase on the wire, enums as strings.

export type ServerStatus = "Running" | "Stopped" | "Pending" | "Error" | "Unknown";

/**
 * A container port published on the host (players connect to nodePort — the
 * field name is a k8s-era leftover kept for wire compatibility).
 */
export interface PortMapping {
  name: string;
  protocol: string;
  containerPort: number;
  nodePort: number;
}

export interface ResourceSpec {
  cpuRequest: string;
  cpuLimit: string;
  memoryRequest: string;
  memoryLimit: string;
}

export interface ServerSummary {
  name: string;
  game: string;
  image: string;
  status: ServerStatus;
  replicas: number;
  createdAt: string;
}

export interface PlayerInfo {
  currentPlayers: number;
  maxPlayers: number;
  currentMap: string | null;
}

export interface ServerDetail extends ServerSummary {
  ports: PortMapping[];
  resources: ResourceSpec | null;
  players: PlayerInfo | null;
}

export interface DeployServerRequest {
  name: string;
  imageTag: string;
  resources?: ResourceSpec | null;
  configOverrides?: Record<string, string> | null;
}

/** A port a game template needs, before a host port has been assigned. */
export interface TemplatePort {
  name: string;
  protocol: string;
  containerPort: number;
}

export type TemplateKind = "Generic" | "MinecraftJava";

export interface GameTemplate {
  displayName: string;
  imageTag: string;
  steamAppId: number | null;
  dataMountPath: string;
  defaultStorageBytes: number;
  defaultPorts: TemplatePort[];
  defaultResources: ResourceSpec;
  defaultConfig: Record<string, string>;
  /** Config keys sourced from the game-secrets Secret; not editable via config. */
  secretKeyRefs: Record<string, string>;
  /**
   * The subset of secretKeyRefs store keys the app generates itself (e.g. RCON
   * passwords). These need no manual entry and don't block start; only the
   * remaining, user-supplied secrets do.
   */
  managedSecretKeys: string[] | null;
  /** Discriminator for templates with a specialized deploy panel. */
  kind: TemplateKind;
  /** Variant image tags (e.g. Minecraft's per-Java tags) that resolve to this template. */
  imageTagAliases: string[] | null;
}

/** Version list for one Minecraft server-software type, newest first. */
export interface MinecraftVersionsResponse {
  latest: string | null;
  versions: string[];
}

/** Trimmed Modrinth search hit (GET /api/minecraft/content/search). */
export interface ModrinthProjectHit {
  slug: string;
  title: string;
  description: string;
  iconUrl: string | null;
  downloads: number;
  projectType: string;
  /** Mod-loader categories (forge, neoforge, fabric, quilt) the project supports. */
  loaders: string[];
}

export interface ModrinthSearchResponse {
  hits: ModrinthProjectHit[];
}

/**
 * Wire shape kept from the k8s era: clusterReachable now means "Docker engine
 * reachable" and namespaceReady mirrors it (namespace is display-only).
 */
export interface ClusterHealth {
  clusterReachable: boolean;
  namespaceReady: boolean;
  namespace: string;
  error: string | null;
}

export interface SetupStatus {
  dockerEngineReachable: boolean;
  /** Metrics come from docker stats, so this tracks engine reachability. */
  metricsAvailable: boolean;
  warnings: string[];
}

/**
 * One secret a server's game requires, with whether a value is set for this
 * server (GET /api/servers/{name}/secrets). Values are never included here.
 * `managed` secrets (e.g. RCON passwords) are auto-generated by the app: they
 * never block start and are shown as reveal/regenerate rather than required entry.
 */
export interface ServerSecretInfo {
  key: string;
  configured: boolean;
  managed: boolean;
}

/** Where the bundled-runtime install currently is (RuntimeSetupService). */
export type RuntimePhase =
  | "Idle"
  | "InstallingWsl"
  | "AwaitingReboot"
  | "DownloadingDistro"
  | "ImportingDistro"
  | "StartingEngine"
  | "Ready"
  | "Failed";

/**
 * Bundled container runtime state (docs/docker-migration.md → Part 2). On
 * Linux only platform + engineReachable are meaningful (native engine).
 */
export interface RuntimeStatus {
  platform: "windows" | "linux";
  wslInstalled: boolean;
  distroImported: boolean;
  engineReachable: boolean;
  mirroredNetworkingConfigured: boolean;
  phase: RuntimePhase;
  /** 0–100 while phase is DownloadingDistro; null otherwise. */
  downloadPercent: number | null;
  error: string | null;
  /** Admin commands the app won't run itself; rendered as copyable snippets. */
  firewallCommands: string[];
}

export interface NodeMetrics {
  cpuUsedMillicores: number;
  cpuCapacityMillicores: number;
  memUsedBytes: number;
  memCapacityBytes: number;
}

export interface PodMetricsInfo {
  serverName: string;
  cpuUsedMillicores: number;
  memUsedBytes: number;
}

export interface MetricsSnapshot {
  available: boolean;
  node: NodeMetrics | null;
  pods: PodMetricsInfo[];
  unavailableReason: string | null;
}

export interface RconCommandResponse {
  response: string;
}

/**
 * One saved backup archive of a server's data volume (WS1). `id` is the
 * archive's timestamp file name, safe to use in a URL path segment.
 */
export interface BackupInfo {
  id: string;
  serverName: string;
  createdAt: string;
  sizeBytes: number;
}

/**
 * The host machine's shareable addresses — used to render copyable "ip:port" join
 * addresses. lanAddresses are the LAN IPv4s in preference order (empty when no LAN
 * adapter is up). publicAddress is the internet-facing IPv4, only reachable by
 * players after the node port is forwarded on the router; null if lookup failed.
 * nodePortRangeStart/End is the backend's whole allocation window — forwarding
 * that range once on the router covers every current and future server.
 */
export interface NetworkInfo {
  lanAddresses: string[];
  publicAddress: string | null;
  nodePortRangeStart: number;
  nodePortRangeEnd: number;
}

// SignalR hub payloads (GameDashboard.Api/RealTime/HubEvents.cs). Every hub
// event carries a single message object argument, not positional arguments.

export interface LogLineMessage {
  serverName: string;
  line: string;
  timestamp: string;
}

export interface ServerStatusChangedMessage {
  serverName: string;
  status: ServerStatus;
  timestamp: string;
}

export interface AutoScaleActionMessage {
  serverName: string;
  action: string;
  reason: string;
  timestamp: string;
}

/**
 * Bytes accumulating on a server's data volume during first deploy (measured by
 * `du` inside the pod). capacityBytes is the PVC size, not the expected install
 * size — show bytesUsed as an absolute, never as a percentage.
 */
export interface DownloadProgressMessage {
  serverName: string;
  bytesUsed: number;
  capacityBytes: number;
  timestamp: string;
}

/** Machine-wide scheduled-backup settings (WS1). */
export interface BackupSettings {
  enabled: boolean;
  intervalMinutes: number;
  retentionCount: number;
}

/** A scheduled backup finished for a server (WS1). */
export interface BackupCompletedMessage {
  serverName: string;
  backupId: string;
  sizeBytes: number;
  timestamp: string;
}
